### ISSUE TITLE
Gtsfm failure cases on tree dataset

### ISSUE THREAD

**Issue by vaishwarya96** [borglab/gtsfm#157]
The reconstruction from GTSFM on my tree dataset is as shown below:

![image](https://user-images.githubusercontent.com/52444619/115515866-d43c3e00-a285-11eb-8be5-a7cd1603b857.png)

Visualizing the tracks and the correspondences, I came across some failure cases, examples of which I am attaching here.
Correspondences:
![4_6](https://user-images.githubusercontent.com/52444619/115516183-28472280-a286-11eb-85c8-5c622364cf31.jpg)
![5_9](https://user-images.githubusercontent.com/52444619/115516219-309f5d80-a286-11eb-8883-cd48ed668dcd.jpg)
Tracks:
![track_22](https://user-images.githubusercontent.com/52444619/115516491-72c89f00-a286-11eb-959b-abd00d75ca41.jpg)
![track_56](https://user-images.githubusercontent.com/52444619/115516521-7b20da00-a286-11eb-86a2-8c245c2ee0d5.jpg)

This is the link to my dataset for reproducing the above results: https://drive.google.com/drive/folders/11cg8mio8zTVu-Kow4rH9RZumv3qJ_Iq1?usp=sharing

**Comment by johnwlambert** [comment]
<img width="480" alt="Screen Shot 2021-04-21 at 10 24 17 AM" src="https://user-images.githubusercontent.com/16724970/115580459-1620b080-a295-11eb-92fa-d73c2584c788.png">

Thanks @vaishwarya96. It looks like COLMAP can reconstruct the tree trunk even without a mask.

It looks like the images dont have any exif data -- is that intentional? Did they ever have any EXIF?

**Comment by johnwlambert** [comment]
It looks like one of the big problems is that we are doing exhaustive matching, when only adjacent frames have shared image content (shared visibility).

When I limit to 1 frame lookahead, I see:

<img width="597" alt="Screen Shot 2021-04-21 at 12 27 54 PM" src="https://user-images.githubusercontent.com/16724970/115588874-35234080-a29d-11eb-880c-41f85bb8d07f.png">

**Comment by vaishwarya96** [comment]
> <img alt="Screen Shot 2021-04-21 at 10 24 17 AM" width="480" src="https://user-images.githubusercontent.com/16724970/115580459-1620b080-a295-11eb-92fa-d73c2584c788.png">
> 
> Thanks @vaishwarya96. It looks like COLMAP can reconstruct the tree trunk even without a mask.
> 
> It looks like the images dont have any exif data -- is that intentional? Did they ever have any EXIF?

The images originally had no exif data. So I'm using the intrinsics calculated by Colmap as input to Gtsfm.

**Comment by ayushbaid** [comment]
> It looks like one of the big problems is that we are doing exhaustive matching, when only adjacent frames have shared image content (shared visibility).

Interesting. Maybe the DA needs to be 'intelligent'? I am wondering if the code I am working on (add a point to a track only when it doesnt blow up the avg reprojection error) will help here.

**Comment by vaishwarya96** [comment]
Here are the results when masking the background in the tree images.
Colmap:
![Screenshot from 2021-04-25 11-31-23](https://user-images.githubusercontent.com/52444619/115988562-a07d5300-a5ba-11eb-89fa-bc467403bce5.png)
Gtsfm:
![Screenshot from 2021-04-25 11-35-24](https://user-images.githubusercontent.com/52444619/115988569-ab37e800-a5ba-11eb-8605-7430d6649e50.png)

**Comment by dellaert** [comment]
This is pretty bad. What stage of the pipeline is going wrong in your opinion? Did you do any investigation?

**Comment by vaishwarya96** [comment]
Similar to the case where the images were not masked, some of the patches from the 2D tracks have outliers: 
![track_56](https://user-images.githubusercontent.com/52444619/116045797-afbfd780-a672-11eb-97ac-a1629e805313.jpg)
![track_531](https://user-images.githubusercontent.com/52444619/116045927-d67e0e00-a672-11eb-94b6-d6ede2570555.jpg)
![track_7537](https://user-images.githubusercontent.com/52444619/116046121-09c09d00-a673-11eb-892a-c05bd750807e.jpg)
Correspondences:
![2_6](https://user-images.githubusercontent.com/52444619/116046236-2957c580-a673-11eb-9121-9786b45b0a02.jpg)
![5_9](https://user-images.githubusercontent.com/52444619/116046381-4db3a200-a673-11eb-98f0-462a627b6455.jpg)

**Comment by johnwlambert** [comment]
@dellaert @ayushbaid  the problem here is solely due to the front-end.

7/19 rotations have ok error, and all translation directions are awful:
<img width="240" alt="Screen Shot 2021-04-26 at 8 54 04 AM" src="https://user-images.githubusercontent.com/16724970/116085574-f6123800-a66c-11eb-8e08-b20f923575b2.png">

This hurts Shonan
<img width="260" alt="Screen Shot 2021-04-26 at 8 50 41 AM" src="https://user-images.githubusercontent.com/16724970/116085724-18a45100-a66d-11eb-8497-86c273877cbb.png">

and kills 1dsfm:
<img width="297" alt="Screen Shot 2021-04-26 at 8 47 32 AM" src="https://user-images.githubusercontent.com/16724970/116085758-21952280-a66d-11eb-9d0e-fc005cc91927.png">

Maybe because the ground is planar? so we are getting all homographies? I looked at 19 correspondences and they all look perfect:

**Comment by dellaert** [comment]
No, COLMAP has no issue with masked data. And ground is not even visible there.

**Comment by johnwlambert** [comment]
I see -- but COLMAP is using a different front-end from us : - ) and it seems superior for this sequence.

This particular tree sequence has very little parallax and it looks like almost all of our matches are on the ground, when we don't use a mask.

**Comment by akshay-krishnan** [comment]
Are we still tracking the tree dataset? Wondering if we should update the status of this issue.

**Comment by ayushbaid** [comment]
Suspect we still have the dataset with us. Closing it for now.
